export interface Assignee {
  name: string
  avatar?: string
  color?: string
}

export interface Task {
  id: string
  checked: boolean
  type?: string
  key: string
  summary: string
  status: "TO DO" | "DONE"
  comments: number
  sprint: string
  assignees: Assignee[]
  dueDate?: string
  labels: string[]
  created: string
  updated: string
  reporter?: Assignee
}

export const mockTasks: Task[] = [
  {
    id: "1",
    checked: true,
    key: "CPW-164",
    summary: "fbsdfhsdfid",
    status: "TO DO",
    comments: 0,
    sprint: "CPW Sprint 9",
    assignees: [],
    labels: [],
    created: "Nov 24, 2025",
    updated: "Nov 25, 2025",
  },
  {
    id: "2",
    checked: true,
    key: "CPW-165",
    summary: "Test",
    status: "TO DO",
    comments: 0,
    sprint: "CPW Sprint 9",
    assignees: [],
    labels: [],
    created: "Nov 24, 2025",
    updated: "Nov 25, 2025",
  },
  {
    id: "3",
    checked: true,
    key: "CPW-166",
    summary: "scsc",
    status: "TO DO",
    comments: 0,
    sprint: "CPW Sprint 9",
    assignees: [],
    labels: [],
    created: "Nov 24, 2025",
    updated: "Nov 25, 2025",
  },
  {
    id: "4",
    checked: true,
    key: "CPW-167",
    summary: "dfdf",
    status: "TO DO",
    comments: 0,
    sprint: "CPW Sprint 9",
    assignees: [],
    labels: [],
    created: "Nov 24, 2025",
    updated: "Nov 25, 2025",
  },
  {
    id: "5",
    checked: true,
    key: "CPW-4",
    summary: "Là một người dùng, tôi muốn có thể đăng nhập bằng bà...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Duy Anh Nguyễn Bá", color: "bg-red-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 18, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "6",
    checked: true,
    key: "CPW-1",
    summary: "Là một người dùng đã có tài khoản, tôi muốn có thể đăng nhập...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Duy Anh Nguyễn Bá", color: "bg-red-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "7",
    checked: true,
    key: "CPW-2",
    summary: "Là một người dùng đang đăng nhập, tôi muốn có thể đăng...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Duy Anh Nguyễn Bá", color: "bg-red-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "8",
    checked: true,
    key: "CPW-3",
    summary: "Là một người dùng đang đăng nhập, tôi muốn có thể thấy...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Duy Anh Nguyễn Bá", color: "bg-red-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "9",
    checked: true,
    key: "CPW-5",
    summary: "Là một người dùng, tôi muốn tạo một Công ty mới để thi...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Duy Anh Nguyễn Bá", color: "bg-red-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "10",
    checked: true,
    key: "CPW-6",
    summary: "Là một người dùng, tôi muốn chính sửa thông tin của mô...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Duy Anh Nguyễn Bá", color: "bg-red-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "11",
    checked: true,
    key: "CPW-8",
    summary: "Là một quản trị viên Công ty, tôi muốn mở các thành viề...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Duy Anh Nguyễn Bá", color: "bg-red-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "12",
    checked: true,
    key: "CPW-9",
    summary: "Là một quản trị viên Công ty, tôi muốn xem danh sách tả...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Zill Đức", color: "bg-yellow-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "13",
    checked: true,
    key: "CPW-10",
    summary: "Là một quản trị viên Công ty, tôi muốn xóa một thành viê...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Zill Đức", color: "bg-yellow-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
  {
    id: "14",
    checked: true,
    key: "CPW-11",
    summary: "Là thành viên, tôi muốn truy cập vào các Workspac...",
    status: "DONE",
    comments: 0,
    sprint: "CPW Sprint 1",
    assignees: [{ name: "Zill Đức", color: "bg-yellow-500" }],
    labels: [],
    created: "Nov 4, 2025",
    updated: "Nov 12, 2025",
    reporter: { name: "Qwan NG", color: "bg-orange-500" },
  },
]
